---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
  namespace: palworld-server
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211"  # Optional but recommended
  PLAYERS: "16"  # Optional but recommended
  SERVER_PASSWORD: "PalworldSafe!"
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: america/chicago
  COMMUNITY: "True"  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  SERVER_NAME: "Bum Boys 2024"
  SERVER_DESCRIPTION: "Rule #1 must bum"
