---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: palworld-server
    app.kubernetes.io/instance: palworld-server
  name: palworld-server
  namespace: palworld-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
        - name: palworld-server
          image: thijsvanloef/palworld-server-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8211
              name: server
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-rcon-password
                  key: rconPassword
          envFrom:
            - configMapRef:
                name: palworld-cm
          volumeMounts:
            - mountPath: /palworld
              name: datadir
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: palworld-server-datadir
